@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 09 13:26:16 -0400 2019
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim top_testbench_behav -key {Behavioral:sim_1:Functional:top_testbench} -tclbatch top_testbench.tcl -view C:/Users/nitheesh/Desktop/Course work/advanced_encryption_algorithm/advanced_encryption_algorithm.srcs/sim_1/imports/advanced_encryption_algorithm.wave/subByte_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
